export const adminJobData = [
  {
    Type: 'Design ',
    Developer: 'Senior Product Designer ',
    Position: 'Position: ',
    Total: 'Total',
    TotalContent: '06',
    Filled: 'Filled',
    FilledContent: '03',
    Candidates: 'Candidates:',
    Active: 'Active',
    ActiveData: '00',
    Contacting: 'Contacting',
    ContactingData: '00',
    Rejected: 'Rejected',
    RejectedData: '00',
    Draft: 'Draft',
  },
  {
    Type: 'Marketing ',
    Developer: 'Marketing Associate ',
    Position: 'Position: ',
    Total: 'Total',
    TotalContent: '06',
    Filled: 'Filled',
    FilledContent: '03',
    Candidates: 'Candidates:',
    Active: 'Active',
    ActiveData: '06',
    Contacting: 'Contacting',
    ContactingData: '06',
    Rejected: 'Rejected',
    RejectedData: '15',
    Draft: 'Draft',
  },
  {
    Type: 'Developer ',
    Developer: 'Senior Product Designer ',
    Position: 'Position: ',
    Total: 'Total',
    TotalContent: '12',
    Filled: 'Filled',
    FilledContent: '15',
    Candidates: 'Candidates:',
    Active: 'Active',
    ActiveData: '10',
    Contacting: 'Contacting',
    ContactingData: '06',
    Rejected: 'Rejected',
    RejectedData: '18',
    Draft: 'Draft',
  },
  {
    Type: 'Developer ',
    Developer: 'Junior Product Designer ',
    Position: 'Position: ',
    Total: 'Total',
    TotalContent: '08',
    Filled: 'Filled',
    FilledContent: '06',
    Candidates: 'Candidates:',
    Active: 'Active',
    ActiveData: '10',
    Contacting: 'Contacting',
    ContactingData: '06',
    Rejected: 'Rejected',
    RejectedData: '18',
    Draft: 'Draft',
  },
]
