const adminJobData = [
  {
    type: 'Design ',
    developer: 'Senior Product Designer ',
    position: 'Position: ',
    total: 'Total',
    totalContent: '06',
    filled: 'Filled',
    filledContent: '03',
    candidates: 'Candidates:',
    active: 'Active',
    activeData: '00',
    contacting: 'In Process',
    contactingData: '00',
    rejected: 'Archived',
    rejectedData: '00',
    draft: 'Draft',
  },
  {
    type: 'Marketing ',
    developer: 'Marketing Associate ',
    position: 'Position: ',
    total: 'Total',
    totalContent: '06',
    filled: 'Filled',
    filledContent: '03',
    candidates: 'Candidates:',
    active: 'Active',
    activeData: '06',
    contacting: 'In Process',
    contactingData: '06',
    rejected: 'Archived',
    rejectedData: '15',
    draft: 'Draft',
  },
  {
    type: 'Developer ',
    developer: 'Senior Product Designer ',
    position: 'Position: ',
    total: 'Total',
    totalContent: '12',
    filled: 'Filled',
    filledContent: '15',
    candidates: 'Candidates:',
    active: 'Active',
    activeData: '10',
    contacting: 'In Process',
    contactingData: '06',
    rejected: 'Archived',
    rejectedData: '18',
    draft: 'Draft',
  },

  {
    type: 'Design ',
    developer: 'Senior Product Designer ',
    position: 'Position: ',
    total: 'Total',
    totalContent: '06',
    filled: 'Filled',
    filledContent: '03',
    candidates: 'Candidates:',
    active: 'Active',
    activeData: '00',
    contacting: 'In Process',
    contactingData: '00',
    rejected: 'Archived',
    rejectedData: '00',
    draft: 'Draft',
  },
  {
    type: 'Marketing ',
    developer: 'Marketing Associate ',
    position: 'Position: ',
    total: 'Total',
    totalContent: '06',
    filled: 'Filled',
    filledContent: '03',
    candidates: 'Candidates:',
    active: 'Active',
    activeData: '06',
    contacting: 'In Process',
    contactingData: '06',
    rejected: 'Archived',
    rejectedData: '15',
    draft: 'Draft',
  },
  {
    type: 'Developer ',
    developer: 'Senior Product Designer ',
    position: 'Position: ',
    total: 'Total',
    totalContent: '12',
    filled: 'Filled',
    filledContent: '15',
    candidates: 'Candidates:',
    active: 'Active',
    activeData: '10',
    contacting: 'In Process',
    contactingData: '06',
    rejected: 'Archived',
    rejectedData: '18',
    draft: 'Draft',
  },
  {
    type: 'Developer ',
    developer: 'Junior Product Designer ',
    position: 'Position: ',
    total: 'Total',
    totalContent: '08',
    filled: 'Filled',
    filledContent: '06',
    candidates: 'Candidates:',
    active: 'Active',
    activeData: '10',
    contacting: 'In Process',
    contactingData: '06',
    rejected: 'Archived',
    rejectedData: '18',
    draft: 'Draft',
  },
  {
    type: 'Developer ',
    developer: 'Junior Product Designer ',
    position: 'Position: ',
    total: 'Total',
    totalContent: '08',
    filled: 'Filled',
    filledContent: '06',
    candidates: 'Candidates:',
    active: 'Active',
    activeData: '10',
    contacting: 'In Process',
    contactingData: '06',
    rejected: 'Archived',
    rejectedData: '18',
    draft: 'Draft',
  },
]

export default adminJobData
