export const CountryData = [
  { label: '+93', value: 'Afganistan' },
  { label: '+61', value: 'Australia' },
  { label: '+43', value: 'Austria' },
  { label: '+55', value: 'Brazil' },
  { label: '+1', value: 'Canada' },
  { label: '+86', value: 'China' },
  { label: '+45', value: 'Denmark' },
  { label: '+20', value: 'Egypt' },
  { label: '+33', value: 'France' },
  { label: '+49', value: 'Germany' },
  { label: '+30', value: 'Greece' },
  { label: '+62', value: 'Indonesia' },
  { label: '+98', value: 'Iran' },
  { label: '+39', value: 'Italy' },
  { label: '+81', value: 'Japan' },
  { label: '+52', value: 'Mexico' },
  { label: '+31', value: 'Netherlands' },
  { label: '+64', value: 'New Zealand' },
  { label: '+47', value: 'Norway' },
  { label: '+7', value: 'Russia' },
]
